# Generated by Django 3.0.4 on 2020-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ham_operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ham_operator',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ham_operator',
            name='licence',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ham_operator',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ham_operator',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
