# Generated by Django 3.0.4 on 2020-05-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ham_operators', '0002_auto_20200422_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ham_Operator',
            new_name='Operator',
        ),
    ]
