# Generated by Django 3.0.3 on 2020-08-26 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ham_operators', '0003_auto_20200504_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='call_sign',
            new_name='call',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='status',
        ),
        migrations.AddField(
            model_name='operator',
            name='membership',
            field=models.CharField(blank=True, choices=[('1', 'Chairman'), ('2', 'Vice-Chairman'), ('3', 'Secretary'), ('4', 'Treasurer'), ('5', 'Member'), ('6', 'Transmission Equipment')], default='5', help_text='Membership Status', max_length=30),
        ),
        migrations.AddField(
            model_name='operator',
            name='nationality',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operator',
            name='licence',
            field=models.CharField(blank=True, choices=[('full', 'Full Licence'), ('noobs', 'Noobs Licence'), ('none', 'No Licence'), ('wait', 'Awaiting Renewal')], default='full', help_text='Licence Status', max_length=30),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operator',
            name='telephone',
            field=models.TextField(),
        ),
    ]
