# Generated by Django 3.0.3 on 2020-08-24 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualslist',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
