# Generated by Django 3.0.3 on 2020-08-24 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manuals', '0002_manualslist_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualslist',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='manualslist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualslist',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='manualslist',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
