# Generated by Django 3.0.3 on 2020-08-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_auto_20200824_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualslist',
            name='author',
        ),
    ]
