# Generated by Django 3.0.3 on 2020-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0004_remove_manualslist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualslist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
