# Generated by Django 3.0.3 on 2020-08-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0005_auto_20200824_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManualsList',
            new_name='Manuals',
        ),
    ]
