# Generated by Django 3.0.3 on 2020-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0007_manuals_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuals',
            name='format',
            field=models.CharField(blank=True, choices=[('.pdf', 'PDF'), ('.doc', 'Ms Word <2017'), ('.docx', 'Ms Word >2017'), ('.jpeg', 'JPEG Image File')], default='.pdf', help_text='Document Type/Format', max_length=6),
        ),
    ]
