# Generated by Django 3.0.3 on 2020-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('box1', models.TextField()),
                ('box2', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='images/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
