# Generated by Django 3.0.3 on 2020-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeitems',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
